// import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Bidly</title>
        <link rel="icon" type="image/x-icon" href="/bidly-images/favicon.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>
      <React.Fragment>
        <CssBaseline />
        <body className={inter.className}>{children}</body>
      </React.Fragment>
    </html>
  )
}
